### PR TITLE
open requestTokenPopup in a real popup instead of tab

### PR DESCRIPTION
**Pull request by slunecniborecek**

### CODE REVIEW

**Comment by naugtur** [comment]
Hi and thanks for contributing.
I'd rather make it an option to let you pass the argument to `window.open`. Would that work tor you?

**Comment by slunecniborecek** [comment]
Sure it would. Are you going to implement it or should I? :) Thanks

**Comment by naugtur** [comment]
I can get down to it next week, so if you have an urgent need for it I'd recommend you implement it. If not, I'll do it next week, release a version and let you know when it's available.

my initial idea was:
```js
requestTokenPopup = function (callback, denied, recvrURL, windowOptionsString)
```

**Comment by slunecniborecek** [comment]
well, I personally don't like this 'put there one more argument' pattern, instead I would change that to function(config){}... But I understand you need to keep the compatibility

**Comment by naugtur** [comment]
Next major release will need to have breaking changes in requesting tokens, as we're moving away from the iframe version, so I'll be able to clean this up.

**Comment by slunecniborecek** [comment]
cool, will keep the modified version in our project as it works the way we want & switch later when ready. Thanks

**Pull request closed without merging**
